---
version: "3"
services:
  speedlogger-web:
    image: brennentsmith/internet-speed-logger
    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./config:/data/config

  speedlogger-runner:
    image: brennentsmith/internet-speed-logger
    depends_on:
      - speedlogger-web
    restart: always
    entrypoint:
      - node
      - run-speedtest.js
      - daemon
    volumes:
      - ./config:/data/config

  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27107
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=speedtest
      - MONGO_INITDB_DATABASE=speedtest
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
